### ISSUE TITLE
[$5000] Build a Moonsama NFT data explorer (with Moonsama)

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/bounties#3]
## Short description

Moonsama NFT on Moonriver has taken the Dotsama NFT space by storm. For this bounty you'd need to develop an explorer for a deep dive to Moonsama data

## Prize Pool
$5000 

## Challenge

The explorer should satisfy the basic needs of Moonsama NFT holders and degens:

- It should be possible to see recent trades and historical volumes
- It should be possible to see current and historical floor price 
- It should be possible to see top holders
- It shoud be possible to sort by rarity
- It should be possible to see Moonsama NFTs hold by an address

This list above is not exhaustive and the teams may decide to implement other features for better UX. 

> 📝Hint:
> It's likely one'd need to use the following Squid features:
> 
> -  [external API](https://github.com/subsquid/squid-external-api-example) 
> -  [custom resolvers](https://docs.subsquid.io/reference/api-extensions)

## Submission Requirements

The data should be taken from a single or multiple Squids deployed to the [Aquarium](https://app.subsquid.io/aquarium)

## Judging criteria

- Creativity and UX 
- Documentation provided

## Resources

- [ERC1155 Docs](https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/)
- [ERC771 Docs](https://ethereum.org/en/developers/docs/standards/tokens/erc-721/)
- [Moonsama Marketplace](https://marketplace.moonsama.com/)
- [Coingecko Price API](https://www.coingecko.com/en/api)
- [Moonriver Subsquid Docs](https://docs.moonbeam.network/builders/integrations/indexers/subsquid/)
- [Subsquid Docs](https://docs.subsquid.io)
- [Sample Moonsama Squid](https://github.com/subsquid/squid/tree/master/test/moonsama-erc721)
- [Sample Squid with Coingecko data](https://github.com/subsquid/squid-external-api-example)

**Comment by biendeveloper** [comment]
Can i start working on this? Or should i apply somewhere first?

**Comment by RaekwonIII** [comment]
Hey @biendeveloper we have created this issue as part of [Polkadot Hackathon North America](https://polkadot-na.devpost.com/?ref_feature=challenge&ref_medium=discover). You can apply there, it's starting today.
This is actually a new bounty, though, a last minute addition, which we are going to try and ask the organization to sneak in.

**Comment by yangwao** [comment]
👀
